hetznercloud/hcloud-python

hcloud/floating_ips/client.py
hcloud/servers/client.py
hcloud/servers/domain.py
tests/unit/servers/conftest.py
tests/unit/servers/test_client.py

Closes #8
This PR allows users to directly get the network and the network mask on the server ipv6 address and it documents/fix the result we give the user instead of returning the API result directly.

Add Network Domains for IPv4 and IPv6 to Server

---

hcloud/__init__.py
hcloud/floating_ips/client.py
hcloud/hcloud.py
hcloud/images/client.py
hcloud/ssh_keys/client.py
tests/unit/test_hcloud.py

Because it looks a little bit funny to have a
`hcloud.hcloud.HcloudAPIException` raised

Rename hcloudAPIException to APIException

---

hcloud/servers/client.py
tests/unit/servers/test_client.py

The PR works as it is. We need to wait on the docs deployment before the integration tests can work.

Fix #19 - SSH Key Error on Server Creation

---

hcloud/ssh_keys/client.py
tests/unit/ssh_keys/test_client.py

This PR adds a new method
`client.ssh_keys.get_by_fingerprint("fingerprint")`
Which allows to get an ssh key by its fingerprint. The fingerprint is unique.
Currently this is the solution we will replace with the new method:
```python
if self.module.params.get("fingerprint") is not None:
result = self.client.ssh_keys.get_all(fingerprint=self.module.params.get("fingerprint"))
if len(result) == 1:
self.hcloud_ssh_key = result[0]
```

Add get_by_fingerprint to SSHKeyClient

---

setup.py

This should fix #40.  @asarubbo could you please test this branch?
Deleting the __init__.py as the solution for this problem was described in https://github.com/enjoy-digital/litex/issues/73.

Remove __init__ file from tests directory

---

docs/api.clients.networks.rst

At the moment on our docs https://hcloud-python.readthedocs.io/en/latest/api.clients.networks.html the NetworkRoute documentation is missing. This fixes the error.

Fix missing hcloud.networks.domain.NetworkRoute documentation

---

CHANGELOG.rst
hcloud/servers/client.py
tests/unit/servers/test_client.py

This fixes a trivial error in parameter handling that prevented image creation

Fix servers.client._create_image error in 'labels' parameter handling

---

CHANGELOG.rst
hcloud/servers/client.py
tests/integration/servers/test_servers.py
tests/unit/servers/test_client.py

The API allows the specification of Network IDs which should be attached to the server private network interface at creation time. However, specifying networks when creating a server is not supported by this package yet.
This PR adds an optional `networks` parameter to the `hcloud.servers.client.ServersClient.create` method and tests based on the ones for the `volumes` paramether.
Let me know, whether something needs to be adjusted. (Got late this night, better review my changes).

Add support for the networks parameter on server creation

---

CHANGELOG.rst
hcloud/load_balancers/domain.py
tests/unit/load_balancers/conftest.py
tests/unit/load_balancers/test_client.py

Add `included_traffic`, `outgoing_traffic` and `ingoing_traffic` properties to Load Balancer domain

Add traffic properties to Load Balancer domain

---

hcloud/servers/domain.py
tests/unit/servers/conftest.py
tests/unit/servers/test_client.py

API provides a field named `primary_disk_size` for servers which was missing.
This field is important if you want to check the possibility of a downgrade for a server.
https://docs.hetzner.cloud/#servers-get-a-server

Add primary_disk_size to Server domain

---

hcloud/hcloud.py
tests/unit/test_hcloud.py

hcloud.Client now reuses the underlying TCP connection instead of establishing a new connection on every request. This was initially found in https://github.com/hetznercloud/hcloud-python/pull/123. This commit superseeds the mentioned MR and fixes the tests.
This was initially found by @SpComb in https://github.com/hetznercloud/hcloud-python/pull/123
Fixes #114

Use requests Session for persistent HTTPS connections

---

requirements/test.txt
tests/unit/actions/test_client.py
tests/unit/certificates/test_client.py
tests/unit/conftest.py
tests/unit/core/test_client.py
tests/unit/datacenters/test_client.py
tests/unit/firewalls/test_client.py
tests/unit/floating_ips/test_client.py
tests/unit/images/test_client.py
tests/unit/isos/test_client.py
tests/unit/load_balancer_types/test_client.py
tests/unit/load_balancers/test_client.py
tests/unit/locations/test_client.py
tests/unit/networks/test_client.py
tests/unit/placement_groups/test_client.py
tests/unit/primary_ips/test_client.py
tests/unit/server_types/test_client.py
tests/unit/servers/test_client.py
tests/unit/ssh_keys/test_client.py
tests/unit/volumes/test_client.py

Python since 3.4 has included mock in the standard library, under the
unittest module. Since the lowest version supported is greater than
that, we can switch to using it and drop one external requirement.

Remove use of external mock module

---

docs/installation.rst

This PR documents an alternative method of installation via [conda-forge](https://conda-forge.org/). Driving some additional customers your way ;) See #113.

document installation path via conda-forge

---

docs/api.helpers.rst
hcloud/helpers/labels.py
hcloud/load_balancers/client.py
tests/unit/helpers/test_labels.py
tox.ini

This implementation is similar to the implementation in the hcloud-go. To give the "user" as much as verbosity as possible i introduced two methods.
- `validate` which is a simple validator that just returns True/False
- `validate_verbose` which also returns the corresponding error message (like which key/value is not correctly formatted)
I decided against calling one of both function in the other and instead duplicate the code. This is based on my feeling that the code would be more complex when we as a sample call validate_verbose in validate. Also, it is slightly more readable imho, but we can discuss this :)
Closes https://github.com/hetznercloud/hcloud-python/issues/153

Add validation helper for Label Values/Keys

---

setup.py

As far as I can tell, we never used this dependency. We only support Python 3+, and the dependency has a known vulnerability and is not maintained.
There is not reason for us to keep it, and we were requested to remove it in #172.

fix: remove unused future dependency

---

hcloud/servers/domain.py

Missing `>` causes link in docs to break: https://hcloud-python.readthedocs.io/en/stable/api.clients.servers.html#hcloud.servers.domain.Server

docs: link to PrivateNet broken

---

hcloud/server_types/domain.py
tests/unit/server_types/conftest.py
tests/unit/server_types/test_client.py

Field was recently added to the API: https://docs.hetzner.cloud/#server-types

feat(server_type): add field for included traffic

---

.github/workflows/release-please.yml
hcloud/__version__.py

Setup release-please to automate creating new tags according to semver rules.
---
The changelog for this project has used RST as the format, but hasnt been filled for a while. We currently add the changelog to the pypi page. Release-please only supports markdown changelogs, so we will get another file `CHANGELOG.md` (in addition to `CHANGELOG.rst`) with the up to date changelog.
As this is outdated/broken right now, I dont plan on fixing it for this PR. Later we could migrate the full changelog to markdown and either only link to it in pypi, or convert it to rst before publishing.

ci: setup release-please

---

MANIFEST.in

Extend the include for documentation assets to `*.js` and `*.svg` files,
to fix building documentation from sdist archives.

Include *.js *.svg static assets in sdist

---

hcloud/helpers/labels.py
tests/unit/helpers/test_labels.py

Related to https://github.com/hetznercloud/hcloud-go/pull/273

fix: adjust label validation for max length of 63 characters

---

.pre-commit-config.yaml
CHANGELOG.md

Overriding the release-please templates is not yet supported, but might be a good idea to be able to comply with prettier's markdown styling.

chore: prettier breaks the release-please changelog format

---

setup.py

The code already expect us to have python >=3.7.
This makes it official, and prevents older version of python to install newer version of the library.
Python 3.7 is EOL in few days https://devguide.python.org/versions/#versions.

feat: bump required python version to >=3.7

---

docs/api.rst
hcloud/__init__.py
hcloud/_exceptions.py
hcloud/actions/domain.py
hcloud/hcloud.py

We want to be able to catch some family of exception, without having to rely on the way too broad `Exception`.
This adds a hierarchy in the exception that might be raised by this library.
- HCloudException
- APIException
- ActionException
- ActionFailedException
- ActionTimeoutException

feat: setup exception hierarchy

---

pyproject.toml

Remove the redundant `wheel` dependency, as it is added by the backend automatically.  Listing it explicitly in the documentation was a historical mistake and has been fixed since, see: https://github.com/pypa/setuptools/commit/f7d30a9529378cf69054b5176249e5457aaf640a

fix: Remove redundant wheel dep from pyproject.toml

---

.readthedocs.yaml

https://blog.readthedocs.com/migrate-configuration-v2/
The new config allow us to specify the package requirements of the docs, this should fix the build process at readthedocs.

chore: add readthedocs config

---

README.rst

Links are pointing to another project, or outdated.

chore: update README links

---

hcloud/_exceptions.py
hcloud/actions/domain.py
tests/unit/actions/test_domain.py

Add more details to the exception message, for example, the `ActionFailedException` didn't print any message:
```
hcloud.actions.domain.ActionFailedException:
```
But will now print:
```
hcloud.actions.domain.ActionFailedException: The pending action failed: Server does not exist anymore
```
This will also provide more details for the Ansible errors.

feat: add details to raised exceptions

---

hcloud/core/domain.py
tests/unit/core/test_domain.py

This helps debugging when printing domain classes.

feat: add __repr__ to domain classes

---

tests/unit/actions/test_client.py

This speeds up the few action tests that run wait_until_finished.
Reduce time from ~5.8s to ~1.7s

test: reduce poll_interval during tests

---

hcloud/placement_groups/client.py

The actions client attribute name is `actions`

fix: invalid attribute in placement group client

---

MANIFEST.in
setup.py

The previously used filename were pointed to invalid names. Fix some linting errors and duplication.

chore: fix package included files

---

MANIFEST.in
hcloud/py.typed

This advertises that our package is typed.
https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages

feat: the package is now typed

---

hcloud/firewalls/client.py

By convention, the _ variable name is used as "ignore/trash" variable. We should not use it for functional variable names.

refactor: do not use _ as functional variable name

---

.gitlab-ci.yml

`make` is missing from the default python alpine images

ci: fix gitlab lint job

---

hcloud/primary_ips/client.py

As the public api document states for Datacenter: "ID or name of Datacenter the Primary IP will be bound to. Needs to be **omitted** if assignee_id is passed.".
since passing the `datacenter` argument to `create` method is required, if you also pass the `assignee_id`, you will get this error:
`in _raise_exception_from_json_content
raise APIException(
hcloud.hcloud.APIException: invalid input in fields 'assignee_id', 'datacenter'`.
so i think the solution is `if assignee_id exist: pop the datacenter from data`.

fix: allow omitting `datacenter` when creating a primary ip

---

setup.py

Fix `setup.py` to exclude installing the `tests`, `examples` and `docs` directories as a top-level Python package, i.e. into:
```
/usr/lib/python*/site-packages/tests
```
Related to 68bb0f2bf33df5e12607b94a306f5ec328685c44

build: exclude top-level directories from being installed

---

hcloud/certificates/client.py
hcloud/floating_ips/client.py
hcloud/images/client.py
hcloud/networks/client.py
hcloud/ssh_keys/client.py
hcloud/volumes/client.py

This fixes the warnings raised by sphinx during the build process. Some rst directives / python references were broken.

docs: fix python references

---

docs/api.clients.actions.rst
hcloud/actions/__init__.py
hcloud/actions/client.py
hcloud/certificates/client.py
hcloud/firewalls/client.py
hcloud/floating_ips/client.py
hcloud/images/client.py
hcloud/load_balancers/client.py
hcloud/networks/client.py
hcloud/primary_ips/client.py
hcloud/servers/client.py
hcloud/volumes/client.py
tests/unit/actions/test_client.py
tests/unit/certificates/test_client.py
tests/unit/firewalls/test_client.py
tests/unit/floating_ips/test_client.py
tests/unit/images/test_client.py
tests/unit/load_balancers/test_client.py
tests/unit/networks/test_client.py
tests/unit/primary_ips/test_client.py
tests/unit/servers/test_client.py
tests/unit/volumes/test_client.py

This implements the new per resources actions endpoints.
Related to https://docs.hetzner.cloud/changelog#2023-06-29-resource-action-endpoints
```py
client.actions.get_by_id() # /actions/{id}
client.<resource>.get_actions_all() # /<resource>/{resource_id}/actions
client.<resource>.get_actions_list() # /<resource>/{resource_id}/actions
client.<resource>.actions.get_all() # /<resource>/actions 
client.<resource>.actions.get_list() # /<resource>/actions
client.<resource>.actions.get_by_id() # /<resource>/actions/{id}
client.<resource>.get_action_by_id() # /<resource>/{resource_id}/actions/{id}
client.actions.get_all() # /actions
client.actions.get_list() # /actions
```
One exception is the primary IPs client, it doesn't include calls to `/<resource>/{resource_id}/actions` or …

feat: implement resource actions clients

---

.readthedocs.yaml
hcloud/actions/client.py

Make sure to catch warnings during the docs build process.

docs: fail on warning

---

docs/api.clients.load_balancers.rst
hcloud/load_balancers/__init__.py
hcloud/load_balancers/client.py
hcloud/load_balancers/domain.py

Related to https://github.com/ansible-collections/hetzner.hcloud/issues/221
Docs: https://docs.hetzner.cloud/#load-balancers-get-a-load-balancer

feat: add load balancer target health status field

---

.gitlab-ci.yml

The pre-commit template does not set the job automatically.

ci: explicitly declare pre-commit job

---

Makefile
hcloud/_client.py
hcloud/actions/client.py
hcloud/core/client.py
hcloud/core/domain.py
hcloud/firewalls/client.py
hcloud/firewalls/domain.py
hcloud/floating_ips/client.py
hcloud/hcloud.py
hcloud/helpers/labels.py
hcloud/images/client.py
hcloud/images/domain.py
hcloud/load_balancers/client.py
hcloud/load_balancers/domain.py
hcloud/networks/client.py
hcloud/primary_ips/client.py
hcloud/servers/client.py
hcloud/servers/domain.py
hcloud/volumes/client.py
pyproject.toml
setup.py

This adds a `make lint` command, running pylint against the code.
This is not part of the pre-commit setup, as pylint needs to import the code to analyze it, therefore needs to be in the same environment.

test: add pylint linter

---

hcloud/actions/client.py
hcloud/certificates/client.py
hcloud/datacenters/client.py
hcloud/firewalls/client.py
hcloud/floating_ips/client.py
hcloud/images/client.py
hcloud/isos/client.py
hcloud/load_balancer_types/client.py
hcloud/load_balancers/client.py
hcloud/locations/client.py
hcloud/networks/client.py
hcloud/placement_groups/client.py
hcloud/primary_ips/client.py
hcloud/server_types/client.py
hcloud/servers/client.py
hcloud/ssh_keys/client.py
hcloud/volumes/client.py
tests/unit/core/test_client.py

This adds the related domain classes as mixins to the bound models.
Provides attributes type hints and the methods of the domain class to the bound model.

feat: add domain attribute type hints to bound models

---

examples/create_server.py
examples/list_servers.py
examples/usage_oop.py
examples/usage_procedurale.py

This allows to run the examples without doing too much copy pasting.

docs: load token from env in examples scripts

---

hcloud/core/client.py

On large objects such as servers, we might generate more than 10 API calls just to print a single server object. This is because the `__repr__` method will recursively generate the `__repr__` for each bound model property and will trigger a `reload` on incomplete models to gather the information from the API.
Related to:
- https://github.com/hetznercloud/hcloud-python/commit/4c227659bfb61551e44c41315b135039576960d3
- https://github.com/hetznercloud/hcloud-python/commit/6d46d06c42e2e86e88b32a74d7fbd588911cc8ad
Fixes #304

fix: prevent api calls when printing bound models

---

hcloud/servers/client.py
hcloud/servers/domain.py
tests/unit/servers/test_client.py

Fixes #181
Allow returning a full response during the server rebuild by passing an option to the rebuild method. The main reason for this is to not break user land and give users time to upgrade. We also don't want to introduce a new method `rebuild2` or `rebuild_with_full_response` to keep the API clean.
The deprecation timeline is the following:
- Introduce the `return_response` argument and deprecated the default behavior (`return_response=False`)
- Wait for the next major release to remove the ability to only return the action and deprecated the usage of the `return_response` argument.
- Wait for the next+1 major release to fully remove the `return_response` argument, or simply leave it unused.

feat: allow returning root_password in servers rebuild

---

hcloud/_exceptions.py

When the API return a `server_error`, it may not provide a message. This ensures that we print `server_none` instead of `None` when printing the exception.

fix: fallback to error code when message is unset

---

hcloud/__init__.py

fix: private object not exported in top level module

---

hcloud/load_balancers/domain.py

https://docs.hetzner.cloud/#load-balancers-get-a-load-balancer

fix: invalid type for load balancer private network property

---

hcloud/core/domain.py
hcloud/firewalls/domain.py
hcloud/floating_ips/domain.py
hcloud/load_balancers/domain.py
hcloud/networks/domain.py
hcloud/placement_groups/domain.py
hcloud/primary_ips/domain.py
hcloud/servers/domain.py
tests/unit/core/test_domain.py

- Add a method to check if 2 domains are equal (only check for same ID or same name)
- Adds the `DomainIdentityMixin` to models that were missing it.

feat: add `has_id_or_name` to `DomainIdentityMixin`

---

hcloud/images/client.py

Add missing warning and sphinx deprecation notice on an already deprecated method.

fix: raise warnings for the `ImagesClient.get_by_name` deprecation

---

hcloud/images/client.py

Allow to get a deprecated image by name.

feat: add `include_deprecated` option when fetching images by name

---

examples/create_server.py

It doesn't make a real impact, as the `id_or_name` method is called on the object later, but to be technically correct, it would be better to pass the server name as `name` instead of `id`.

docs: cx11 is name, not an id

---

README.md
examples/create_server.py
examples/get_server_metrics.py
examples/usage_oop.py
examples/usage_procedurale.py

Learn more: https://docs.hetzner.cloud/changelog#2024-06-06-old-server-types-with-shared-intel-vcpus-are-deprecated
- Updated docs with newer server types

chore: replace deprecated server type with cx22

---

.github/release-please-config.json
docs/conf.py
hcloud/__init__.py
hcloud/__version__.py
hcloud/_client.py
hcloud/_version.py
setup.py

feat!: move `hcloud.__version__.VERSION` to `hcloud.__version__`

---

hcloud/_client.py
tests/unit/test_client.py

This simplifies the API of the request method, and fixes the return values to always be a dict.

feat!: return empty dict on empty responses in `Client.request`

---

hcloud/_client.py
hcloud/actions/client.py
tests/unit/actions/test_client.py

Prevent the user to read or edit the poll_interval after the client has been constructed.

feat!: make `Client.poll_interval` a private property

---

hcloud/_client.py

The argument was already marked as internal, this makes sure we follow the private name convention.

feat!: make `Client.request` `tries` a private argument

---

hcloud/primary_ips/client.py
tests/unit/primary_ips/test_client.py

Create a primary ips assigned to a resource without having to pass the datacenter argument.

fix!: make `datacenter` argument optional when creating a primary ip

---

hcloud/_client.py
hcloud/actions/client.py
tests/unit/actions/test_client.py

Allow using a computed poll_interval sleeping time, (e.g. exponential back off) when polling actions.

feat: allow using a custom poll_interval function

---

hcloud/_client.py
hcloud/_exceptions.py
tests/unit/test_client.py

- Do not use helper functions to raise exceptions,
- Add the request trace ID to the API exceptions,
- Refactor the code.

feat: add `trace_id` to API exceptions

---

hcloud/servers/client.py
tests/unit/servers/test_client.py

The single action returned was deprecated and is now removed in favor of the full rebuild response with a root password.

feat!: return full rebuild response in `Client.servers.rebuild`

---

hcloud/_client.py
hcloud/_exceptions.py
tests/unit/test_client.py

I learned that we should not use the trace_id name for a correlation_id.
I scoped this change as a fix, as the correltation_id is only used internally.

fix: rename `trace_id` variable to `correlation_id` 

---

hcloud/servers/client.py

:man_facepalming: Missing changes from #406

fix: clean unused arguments in the `Client.servers.rebuild` method

---

hcloud/primary_ips/client.py
tests/unit/primary_ips/test_client.py

The `assignee_type` is always required when creating a primary IP, also when creating an IP in a datacenter (without `assignee_id`).

fix: `assignee_type` is required when creating a primary ip

---

hcloud/_client.py
tests/unit/test_client.py

The ansible integrations tests for `certificate_info` were silently failing because the `details` was missing from the API error.
https://dev.azure.com/ansible/hetzner.hcloud/_build/results?buildId=116526&view=logs&j=790943b1-2131-5e64-166b-e241853dcaf1&t=4ad41445-2459-50a0-f330-095184dc0a34&l=641

fix: details are optional in API errors

---

hcloud/__init__.py
hcloud/_client.py
tests/unit/test_client.py

- Implement the same backoff function as in the hcloud-go libary
- Preparation work to change the retry backoff function to use an exponential backoff interval.
- Rename PollIntervalFunction to BackoffFunction, as it is not only used for polling.

feat: add exponential and constant backoff function

---

hcloud/_client.py
tests/unit/test_client.py

Preparation work to implement a more advanced retry policy when doing requests.

refactor: do not recurse for request retries

---

hcloud/actions/domain.py
hcloud/certificates/domain.py
hcloud/core/domain.py
hcloud/datacenters/domain.py
hcloud/deprecation/domain.py
hcloud/firewalls/domain.py
hcloud/floating_ips/domain.py
hcloud/images/domain.py
hcloud/isos/domain.py
hcloud/load_balancer_types/domain.py
hcloud/load_balancers/domain.py
hcloud/locations/domain.py
hcloud/metrics/domain.py
hcloud/networks/domain.py
hcloud/placement_groups/domain.py
hcloud/primary_ips/domain.py
hcloud/server_types/domain.py
hcloud/servers/domain.py
hcloud/ssh_keys/domain.py
hcloud/volumes/domain.py
tests/unit/core/test_client.py
tests/unit/core/test_domain.py

Allow differences between the classes slots and the API object properties.

refactor: allow differences between api object properties and slots

---

hcloud/_client.py
tests/unit/test_client.py

Replace current `retries * retry_interval` backoff with a truncated exponential backoff algorithm.

feat: use exponential backoff when retrying requests

---

hcloud/server_types/domain.py

The API has been updated to provide a better insight and more flexibility for displaying the pricing of traffic for servers and load balancers.
The old fields are deprecated and will be set to `None` in the API on 2024-08-05.
You can learn more about this change in [our changelog](https://docs.hetzner.cloud/changelog#2024-07-25-cloud-api-returns-traffic-information-in-different-format).

feat: deprecate `ServerType` `included_traffic` property

---

hcloud/actions/client.py

Do not sleep before checking for the reloaded action status.

fix: do not sleep before checking for the reloaded action status

---

hcloud/_client.py

Ensure the function does not receive 2 arguments (self, retries)

fix: mark client retry backoff function as static

---

hcloud/networks/domain.py

- Update the properties documentation
- Add deprecation warning for long deprecated `TYPE_SERVER`.

fix: update network subnet types

---

hcloud/_client.py
tests/unit/test_client.py

Implement a retry handler to retry requests based on an internal retry policy.
The retry policy will evolve over time to cover more use cases, but for now we want to start simple, and maybe someday allow users to tweak the retry policy.
Related to https://github.com/hetznercloud/hcloud-go/pull/470
BEGIN_COMMIT_OVERRIDE
feat: retry requests when the api gateway errors (#430)
feat: retry requests when the network timed outs (#430)
feat: retry requests when the rate limit was reached (#430)
feat: retry requests when the api returns a conflict error (#430)
END_COMMIT_OVERRIDE

feat: implement retry policy

---

hcloud/load_balancer_types/domain.py
hcloud/server_types/domain.py

fix: prices properties are list of dict

---

hcloud/floating_ips/client.py

The type for the floating ip label was wrong. Its now changed to the type in the comments and works as expected.

fix: change floating ip labels type to `dict[str, str]`

---

README.md
hcloud/_client.py

Users must subscribe to our changelog, or they might not be notified about additions, deprecations and removals.

docs: add links to api changelog

---

hcloud/actions/__init__.py
hcloud/certificates/__init__.py
hcloud/core/__init__.py
hcloud/datacenters/__init__.py
hcloud/deprecation/__init__.py
hcloud/firewalls/__init__.py
hcloud/floating_ips/__init__.py
hcloud/helpers/__init__.py
hcloud/images/__init__.py
hcloud/isos/__init__.py
hcloud/load_balancer_types/__init__.py
hcloud/load_balancers/__init__.py
hcloud/locations/__init__.py
hcloud/metrics/__init__.py
hcloud/networks/__init__.py
hcloud/placement_groups/__init__.py
hcloud/primary_ips/__init__.py
hcloud/server_types/__init__.py
hcloud/servers/__init__.py
hcloud/ssh_keys/__init__.py
hcloud/volumes/__init__.py
pyproject.toml

First step towards #479:
* Explicitly re-export modules.

refactor: explicitly reexport modules

---

hcloud/core/client.py
hcloud/core/domain.py
tests/unit/core/test_client.py
tests/unit/core/test_domain.py

This allows easier introspection of API responses. Very useful for unit-testing behaviour of wrappers of hcloud.

feat: add equality checks to domains

---

hcloud/_exceptions.py
hcloud/actions/domain.py
tests/unit/test_exceptions.py

Follow the action error message pattern that we used in hcloud-go.

feat: improve exception messages
