hetznercloud/hcloud-python

hcloud/hcloud.py, hcloud/version.py, tests/integration/conftest.py, tests/unit/test_hcloud.py
Add possibility to configure the endpoint 
Add possibility to set the application name
Closes #7, Closes #6
=> Add possibility to configure endpoint and application name

.travis.yml
=> linting with travis lint

Makefile, docs/api.rst, docs/index.rst, docs/samples.rst, examples/create_server.py, examples/list_servers.py, examples/usage_oop.py, examples/usage_procedurale.py, hcloud/__init__.py, hcloud/core/client.py, hcloud/hcloud.py, tests/integration/conftest.py, tests/unit/conftest.py, tests/unit/test_hcloud.py
=> Rename Client & Let APIException return a string

setup.py
This should fix the errors reported in #53
=> Allow the usage of multiple requests versions.

setup.py
=> Fixes too strict dateutil requirement (#63)

CHANGELOG.rst, setup.py
=> Fixes too strict future requirement

setup.py
Closes https://github.com/hetznercloud/hcloud-python/issues/87.
=> Support requests 2.23

hcloud/actions/domain.py, hcloud/floating_ips/client.py
just tiny spelling fix, as found by a bot.
=> spelling fixes

CHANGELOG.rst, hcloud/images/client.py, tests/unit/images/test_client.py
=> Feature: Add `include_deprecated` filter to `get_list` and `get_all` on `ImagesClient`

CHANGELOG.rst, hcloud/networks/client.py, hcloud/networks/domain.py, tests/unit/networks/test_client.py
=> Feature: Add vSwitch support to `add_subnet` on `NetworksClient`

hcloud/firewalls/client.py
Fix wrong docstring as found in #115
=> Fix wrong doc string in FirewallsClient

docs/api.clients.certificates.rst, docs/api.clients.load_balancer_types.rst, docs/api.clients.load_balancers.rst, docs/conf.py, hcloud/load_balancers/client.py, hcloud/load_balancers/domain.py
=> Fix documentation generation issues

hcloud/firewalls/domain.py
=> Add support for Firewall protocols ESP and GRE

hcloud/images/domain.py
=> Add image type app to image documentation

hcloud/firewalls/client.py, hcloud/firewalls/domain.py, tests/unit/firewalls/conftest.py, tests/unit/firewalls/test_client.py
=> Add support for Resources on FirewallClient.create

hcloud/firewalls/client.py, hcloud/firewalls/domain.py, tests/unit/firewalls/conftest.py, tests/unit/firewalls/test_client.py
=> Firewall: Add label selector resource support

setup.py
This includes the remove of the upper boundary.
Closes #155 
=> Simplify Requirement Constraints

.github/workflows/code_style.yml, .github/workflows/release.yml, .github/workflows/unit_test.yml
=> Update Github Actions

README.rst
=> docs: use venv for the dev setup

.github/workflows/release.yml, pyproject.toml
Use the PEP 517 build system.
https://peps.python.org/pep-0517/
=> feat: adhere to PEP 517

hcloud/_compat.py, hcloud/actions/domain.py, hcloud/certificates/domain.py, hcloud/deprecation/domain.py, hcloud/firewalls/domain.py, hcloud/floating_ips/domain.py, hcloud/images/domain.py, hcloud/isos/domain.py, hcloud/load_balancers/domain.py, hcloud/networks/domain.py, hcloud/placement_groups/domain.py, hcloud/primary_ips/domain.py, hcloud/servers/domain.py, hcloud/ssh_keys/domain.py, hcloud/volumes/domain.py, tests/unit/core/test_domain.py, tests/unit/networks/test_client.py, tests/unit/test_compat.py, tests/unit/volumes/test_client.py
=> fix: handle Z timezone in ISO8601 datetime format

hcloud/hcloud.py, tests/unit/test_hcloud.py
Small code improvement, and start typings the code.
In addition, this will help vendoring this package in the ansible collection, e.g. with the type definitions.
=> refactor: improve hcloud.Client

hcloud/actions/client.py, hcloud/certificates/client.py, hcloud/datacenters/client.py, hcloud/firewalls/client.py, hcloud/floating_ips/client.py, hcloud/images/client.py, hcloud/isos/client.py, hcloud/load_balancer_types/client.py, hcloud/load_balancers/client.py, hcloud/locations/client.py, hcloud/networks/client.py, hcloud/placement_groups/client.py, hcloud/primary_ips/client.py, hcloud/server_types/client.py, hcloud/servers/client.py, hcloud/ssh_keys/client.py, hcloud/volumes/client.py
This adds some type hints for the clients, should help development (I can now jump to references using my IDE).
=> refactor: add Clients type hints

hcloud/certificates/client.py, hcloud/ssh_keys/client.py
The doc strings were at the wrong place.
=> fix: ineffective doc strings

hcloud/certificates/client.py, hcloud/firewalls/client.py, hcloud/floating_ips/client.py, hcloud/images/client.py, hcloud/load_balancer_types/client.py, hcloud/load_balancers/client.py, hcloud/networks/client.py, hcloud/placement_groups/client.py, hcloud/primary_ips/client.py, hcloud/servers/client.py, hcloud/volumes/client.py
Replace strings `.format()` with f-strings.
=> refactor: use f-string

hcloud/_client.py
Add a global request timeout option.
Fixes #262
=> feat: add global request timeout option

.github/workflows/release.yml, setup.py
- fix: missing long_description content_type in setup.py
- ci: check release process in pull requests
=> fix: missing long_description content_type in setup.py

hcloud/firewalls/__init__.py, hcloud/firewalls/client.py, hcloud/firewalls/domain.py
Add the read-only `applied_to_resources` field to `FirewallResource`
https://docs.hetzner.cloud/#firewalls-get-a-firewall
=> feat(firewalls): add `applied_to_resources` to `FirewallResource`

hcloud/datacenters/domain.py, hcloud/firewalls/domain.py
Some domains class were not inheriting from the base domain class.
=> fix: missing BaseDomain base class inheritance

.github/workflows/test.yml, .gitlab-ci.yml, setup.py, tox.ini
=> feat: support python 3.12

hcloud/isos/domain.py, tests/unit/isos/conftest.py, tests/unit/isos/test_client.py, tests/unit/isos/test_domain.py
=> feat: prepare for iso deprecated field removal

.github/workflows/release.yml
=> ci: publish package to PyPI using OIDC

README.md, docs/index.md, docs/upgrading.md
Add upgrade notes for the new v2 release.
=> docs: add v2 upgrade notes

.gitlab-ci.yml
- Only run on feature branches.
=> ci: update gitlab ci

CHANGELOG.md
Those were missing from the release please PR.
=> docs: add api changes note in changelog
